// conkers — boot spec. The brain's boot table is generated by its build from
// every cartridge's build.zon, so this cartridge owns its own construct /
// register / destroy, as cartridges/chess/brain/boot_spec.zig does.
//
// Phase 1: the verbs are pure and the walkers keep no durable state, so the
// bundle is just the walkers' State. Successor cells are returned to the
// caller; persisting them is the LINEAR cell graph's job (P3d, later).

const std = @import("std");
const verb_dispatcher = @import("verb_dispatcher");
const cartridge_spec = @import("cartridge_spec");
const walkers = @import("conkers_walkers");

pub const Bundle = struct {
    state: walkers.State,
};

fn construct(d: cartridge_spec.BootDeps) anyerror!*anyopaque {
    const b = try d.allocator.create(Bundle);
    b.* = .{ .state = .{} };
    return b;
}

fn register(h: *anyopaque, reg: *verb_dispatcher.Registry) anyerror!void {
    const b: *Bundle = @ptrCast(@alignCast(h));
    try walkers.registerAll(reg, &b.state);
}

fn destroy(a: std.mem.Allocator, h: *anyopaque) void {
    const b: *Bundle = @ptrCast(@alignCast(h));
    a.destroy(b);
}

pub const spec: cartridge_spec.Spec = .{
    .id = "conkers",
    .surface = .walkers,
    .construct = construct,
    .register = register,
    .destroy = destroy,
};

// ─── Tests ───────────────────────────────────────────────────────────────────

const testing = std.testing;

fn testClock() i64 {
    return 1_000_000;
}

test "construct → register → destroy wires the four verbs and leaks nothing" {
    const h = try spec.construct(.{ .allocator = testing.allocator, .clock_fn = testClock });
    defer spec.destroy(testing.allocator, h);
    var reg = verb_dispatcher.Registry.init(testing.allocator);
    defer reg.deinit();
    try spec.register(h, &reg);
    try testing.expectEqual(@as(usize, 4), reg.count());
    try testing.expect(reg.hasExtension("conkers"));
}
